// GENERATED BY webrogue-event-apigen. DO NOT EDIT MANUALLY
#include <stddef.h>
#include <stdint.h>

void webrogue_gfx_present();
void webrogue_gfx_make_window();
void webrogue_gfx_window_size(int *width, int *height);
void webrogue_gfx_gl_size(int *width, int *height);
void webrogue_gfx_init_gl();
void *webrogueGLLoader(const char *procname);

// Events
struct webrogue_event_mouse_down {
    uint32_t x;
    uint32_t y;
    uint32_t button;
};
struct webrogue_event_mouse_up {
    uint32_t x;
    uint32_t y;
    uint32_t button;
};
struct webrogue_event_mouse_motion {
    uint32_t x;
    uint32_t y;
};
struct webrogue_event_quit {
};
enum webrogue_event_type {
    WEBROGUE_EVENT_TYPE_INVALID = 0,
    WEBROGUE_EVENT_TYPE_MOUSE_DOWN = 1,
    WEBROGUE_EVENT_TYPE_MOUSE_UP = 2,
    WEBROGUE_EVENT_TYPE_MOUSE_MOTION = 3,
    WEBROGUE_EVENT_TYPE_QUIT = 4,
};
typedef struct webrogue_event {
    enum webrogue_event_type type;
    union {
        struct webrogue_event_mouse_down mouse_down;
        struct webrogue_event_mouse_up mouse_up;
        struct webrogue_event_mouse_motion mouse_motion;
        struct webrogue_event_quit quit;
    } inner;
} webrogue_event;

webrogue_event webrogue_gfx_poll();
