// GENERATED BY webrogue-event-apigen. DO NOT EDIT MANUALLY
#include <stddef.h>
#include <stdint.h>

typedef uint32_t wr_window_handle;

void webroguegfx_make_window(wr_window_handle *out_window);
void webroguegfx_window_size(wr_window_handle window, int *width, int *height);
void webroguegfx_gl_size(wr_window_handle window, int *width, int *height);

// Events
struct webrogue_event_mouse_button {
    uint32_t button;
    uint8_t down;
    uint32_t x;
    uint32_t y;
};
struct webrogue_event_mouse_motion {
    uint32_t x;
    uint32_t y;
};
struct webrogue_event_key {
    uint8_t down;
    uint32_t scancode;
};
struct webrogue_event_quit {
};
struct webrogue_event_window_resized {
};
struct webrogue_event_gl_resized {
};
struct webrogue_event_text_input {
    uint8_t c;
};
enum webrogue_event_type {
    WEBROGUE_EVENT_TYPE_INVALID = 0,
    WEBROGUE_EVENT_TYPE_MOUSE_BUTTON = 1,
    WEBROGUE_EVENT_TYPE_MOUSE_MOTION = 2,
    WEBROGUE_EVENT_TYPE_KEY = 3,
    WEBROGUE_EVENT_TYPE_QUIT = 4,
    WEBROGUE_EVENT_TYPE_WINDOW_RESIZED = 5,
    WEBROGUE_EVENT_TYPE_GL_RESIZED = 6,
    WEBROGUE_EVENT_TYPE_TEXT_INPUT = 7,
};
typedef struct webrogue_event {
    enum webrogue_event_type type;
    union {
        struct webrogue_event_mouse_button mouse_button;
        struct webrogue_event_mouse_motion mouse_motion;
        struct webrogue_event_key key;
        struct webrogue_event_quit quit;
        struct webrogue_event_window_resized window_resized;
        struct webrogue_event_gl_resized gl_resized;
        struct webrogue_event_text_input text_input;
    } inner;
} webrogue_event;

webrogue_event webroguegfx_poll();
