# Cmake toolchain description file for the Makefile

set(CMAKE_SYSTEM_NAME WASI)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR wasm32)
set(triple wasm32-wasi-threads)
set(COMPILE_FLAGS "-pthread -I/opt/wasip1/include -mllvm -wasm-enable-sjlj -mllvm -wasm-use-legacy-eh=false")
set(LINK_FLAGS "-Wl,-L/opt/wasip1/lib")
set(CMAKE_C_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} ${COMPILE_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} ${COMPILE_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${CMAKE_EXE_LINKER_FLAGS_INIT} -Wl,--import-memory")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${CMAKE_EXE_LINKER_FLAGS_INIT} -Wl,--export-memory")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${CMAKE_EXE_LINKER_FLAGS_INIT} ${LINK_FLAGS}")
set(CMAKE_LINKER_FLAGS_INIT "${CMAKE_LINKER_FLAGS_INIT} ${LINK_FLAGS}")

if(NOT WASI_SDK_PREFIX)
    set(WASI_SDK_PREFIX /opt/wasip1)
endif()

set(CMAKE_C_COMPILER ${WASI_SDK_PREFIX}/bin/clang)
set(CMAKE_CXX_COMPILER ${WASI_SDK_PREFIX}/bin/clang++)
set(CMAKE_ASM_COMPILER ${WASI_SDK_PREFIX}/bin/clang)
set(CMAKE_AR ${WASI_SDK_PREFIX}/bin/llvm-ar)
set(CMAKE_RANLIB ${WASI_SDK_PREFIX}/bin/llvm-ranlib)
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER_TARGET ${triple})
set(CMAKE_ASM_COMPILER_TARGET ${triple})

# Don't look in the sysroot for executables to run during the build
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# Only look in the sysroot (not in the host paths) for the rest
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_PREFIX_PATH /opt/wasip1)
set(CMAKE_FIND_ROOT_PATH /opt/wasip1/lib)
list(APPEND CMAKE_MODULE_PATH /opt/wasip1/lib/cmake)
set(SDL2_INCLUDEDIR ${CMAKE_PREFIX_PATH}/include/SDL2)
set(PNG_PNG_INCLUDE_DIR ${CMAKE_PREFIX_PATH}/include/libpng16)
set(PNG_LIBRARY ${CMAKE_PREFIX_PATH}/lib/libpng.a)
set(ZLIB_INCLUDE_DIR /opt/wasip1/include)
set(LIBRESOLV_LIBRARY ${WASI_SDK_PREFIX}/share/wasi-sysroot/lib/wasm32-wasip1-threads/libresolv.a)
set(PTHREAD_LIBRARY ${WASI_SDK_PREFIX}/share/wasi-sysroot/lib/wasm32-wasip1-threads/libpthread.a)
